# Generated by Django 3.2 on 2023-05-16 22:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
