# Generated by Django 4.1.8 on 2023-04-14 10:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sentences',
            fields=[
                ('sentence', models.CharField(max_length=50, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(2)])),
                ('word', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('translation', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('Hword', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('level', models.IntegerField()),
                ('unit', models.IntegerField()),
            ],
        ),
    ]
