# Generated by Django 4.1.8 on 2023-04-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='learn_unit',
        ),
        migrations.RemoveField(
            model_name='account',
            name='level',
        ),
        migrations.AddField(
            model_name='account',
            name='userLevel',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='account',
            name='userUnit',
            field=models.IntegerField(default=1),
        ),
    ]
