# Generated by Django 4.1.8 on 2023-04-12 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_account_learn_unit_remove_account_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_teacher',
        ),
    ]
