# Generated by Django 4.1.8 on 2023-04-12 14:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_account_is_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentnce', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('word', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('tranlation', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('Hword', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
            ],
        ),
    ]
