# Generated by Django 4.1.8 on 2023-04-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_sentence'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='level',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sentence',
            name='unit',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
