# Generated by Django 4.1.8 on 2023-04-12 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_sentence_level_sentence_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentence',
            old_name='sentnce',
            new_name='sentence',
        ),
        migrations.RenameField(
            model_name='sentence',
            old_name='tranlation',
            new_name='translation',
        ),
    ]
