# Generated by Django 4.1.8 on 2023-04-12 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_sentnce_sentence_sentence_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sentence',
        ),
    ]
