# Generated by Django 3.2 on 2023-04-20 17:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='classroom',
            new_name='teacher',
        ),
        migrations.AddField(
            model_name='student',
            name='hashkey',
            field=models.CharField(default=None, max_length=5, validators=[django.core.validators.MinLengthValidator(2)]),
            preserve_default=False,
        ),
    ]
