# Generated by Django 3.2 on 2023-04-23 07:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0003_remove_student_studentunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(default=None, max_length=50, validators=[django.core.validators.MinLengthValidator(2)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(default=None, max_length=50, validators=[django.core.validators.MinLengthValidator(2)]),
            preserve_default=False,
        ),
    ]
