# Generated by Django 3.2 on 2023-04-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0004_auto_20230423_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
    ]
