# Generated by Django 3.2 on 2023-04-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0005_classroom_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='studentLevel',
        ),
        migrations.AddField(
            model_name='classroom',
            name='classLevel',
            field=models.IntegerField(default=1),
        ),
    ]
