# Generated by Django 3.2 on 2023-05-11 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0006_auto_20230426_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.AlterField(
            model_name='student',
            name='hashkey',
            field=models.CharField(max_length=6, unique=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
