# Generated by Django 4.1.4 on 2022-12-20 11:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='learn_unit',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='account',
            name='level',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
