# Generated by Django 4.1.6 on 2023-02-12 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_learn_unit_alter_account_level'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
