# Generated by Django 4.1.6 on 2023-02-12 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='email',
        ),
    ]
